# Generated by Django 4.1.4 on 2023-01-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appolo', '0002_alter_usuario_temaprogreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='TemaProgreso',
            new_name='temaProgreso',
        ),
    ]
