# Generated by Django 4.1.4 on 2023-02-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appolo', '0004_usuario_estiloaprendizaje2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
